### ISSUE TITLE
Allow step by step in playground + show variables 

### ISSUE THREAD

**Issue by JanEricNitschke** [jaspervdj/turnstyle#2]
I wanted to have a look at this and see if I can write something myself and I think it would be extremely helpful if one could go step by step through the playground and also see what variables have been defined with which value and so on.

It would probably also be awesome to be able to interactively build the images instead of uploading them.

Lastly, instructions of how to install the Interpreter locally would be great.

**Comment by jaspervdj** [comment]
Hi @JanEricNitschke, and thanks for the interest!  I think of all of these are very good requests.

Ask one: could you split this into multiple issues so we can track progress?  I can see:

- Add "step" button in playground
- Add variable view in playground
- Allow editing programs in the playground
- Add instructions for locally installing the interpreter

I'm happy to take a look at all of them, but since this is a purely fun project I'm not sure when this will happen.  Are you interested in helping with any of these?  I'm happy to offer guidance as well.

**Comment by JanEricNitschke** [comment]
Hi @jaspervdj thanks for the quick reply. I will split this up when I'm on my PC again.

I'd definitely love to help here if you have some guidance. But I also can't guarantee how much time I can in at the moment as I am also fairly busy.

**Comment by JanEricNitschke** [comment]
Closing in favor of https://github.com/jaspervdj/turnstyle/issues/3 https://github.com/jaspervdj/turnstyle/issues/4 https://github.com/jaspervdj/turnstyle/issues/5 https://github.com/jaspervdj/turnstyle/issues/6
